name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: "Publish release"
    runs-on: "ubuntu-latest"

    environment:
      name: deploy

    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
          python-version: 3.8
      - name: Install build dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install build twine
      - name: "Build package"
        run: python -m build
      - name: "Publish to PyPI"
        run: twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
